.github/workflows/pr.yml
.github/workflows/release.yml
src/voting-metadata-api/audit-resolve.json
src/voting-metadata-api/package-lock.json
src/voting-metadata-api/package.json

The vulnerability is in a package we aren't shipping with the app (we use whatever aws sdk is present in lambda)

Added audit resolution to api project and ignored new vulnerability

---

.github/workflows/release.yml
src/dapp/.env.template
src/dapp/src/components/siteHeader.tsx
src/dapp/src/features/rounds/NoRounds.tsx
src/dapp/src/features/rounds/index.tsx
src/dapp/src/features/wallet/state.ts
src/dapp/src/main.tsx
src/dapp/src/shared/api.ts
src/dapp/src/shared/router/RequireCreator.tsx
src/dapp/src/vite-env.d.ts

creator in allowlist:
vote caster not in allowlist:
Signed out:

Add creator allowlist

---

src/dapp/src/features/vote/VoteResults.tsx
src/dapp/src/features/vote/index.tsx

- Make voting page wider.
- Calculate vote bar widths as percentages
-  Fix bug where max count was same for all questions

Make voting page wider

---

src/xgov-dapp/src/features/vote/AlgoStats.tsx
src/xgov-dapp/src/features/vote/VoteResults.tsx
src/xgov-dapp/src/features/vote/VotingStats.tsx
src/xgov-dapp/src/features/vote/VotingTime.tsx
src/xgov-dapp/src/features/vote/index.tsx
src/xgov-dapp/tailwind.config.cjs

Also rejig the wording on the voting time

Add vote & algo stats to the results page

---

src/xgov-dapp/src/features/rounds/VotingRoundTile.tsx
src/xgov-dapp/src/features/vote/index.tsx
src/xgov-dapp/src/features/wallet/manualSigningProvider.ts
src/xgov-dapp/src/shared/api.ts
src/xgov-dapp/src/shared/question-encoding.ts
src/xgov-dapp/vite.config.ts

Minor fixes to clear out the console logs and improve page routing
- Implement `buffer` polyfill with resolver
- Add missing `key` to mapped component in `Vote`
- Use `Link` for shallow routing in `VotingRoundTile`

minor fixes for xgov-dapp

---

.github/workflows/pr.yml
.github/workflows/release.yml

Uses a flow-based model for CI/CD. All commits are staged in `develop` with a testing environment
- Testing URL: https://testnet.xgov.algorand.foundation/

chore: move to a flow-based model

---

.github/workflows/pr.yml
.github/workflows/release.yml

Moves from a trunk based development to a flow-based model

chore: deploy flow-based ci/cd

---

src/xgov-dapp/src/features/vote/index.tsx
src/xgov-dapp/src/types/index.d.ts

- Add `shuffle` method to `Array` prototype (Fisher-Yates algorithm)
- Shuffle proposals before rendering 
- JIRA: [AF-65](https://algorandfoundation.atlassian.net/browse/AF-65?atlOrigin=eyJpIjoiMDM1ZjkxYjI4YzViNDMzYTg1YTI3MGQyNDMxZjA4YWQiLCJwIjoiaiJ9)
[AF-65]: https://algorandfoundation.atlassian.net/browse/AF-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: randomize proposals

---

src/xgov-dapp/src/features/wallet/ConnectWallet.tsx
src/xgov-dapp/src/utils/useAlgoWalletProvider.ts

- adds check for extension
- displays "install" button when exodus extension is not installed
- uses "WalletConnect" for QR codes/Deep Links
- uses "Exodus Extension" when it is installed
- #96 
Related Issues:
- https://algorandfoundation.atlassian.net/browse/AF-72

feat: add exodus wallet integration

---

src/xgov-dapp/src/features/vote/index.tsx

- Pin passed proposals to the bottom of the voting session page
- JIRA: [AF-70](https://algorandfoundation.atlassian.net/browse/AF-70?atlOrigin=eyJpIjoiMzY3MzljZTA1ZmZiNDZiMWI1MTAxMjJlYTE2OTc2MmUiLCJwIjoiaiJ9)
[AF-70]: https://algorandfoundation.atlassian.net/browse/AF-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Pin passed proposals to bottom

---

src/dapp/package-lock.json
src/xgov-dapp/package-lock.json
src/xgov-dapp/src/features/vote/index.tsx

- Move hooks before any component return statement to fix `Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.`
- Jira: [AF-98](https://algorandfoundation.atlassian.net/browse/AF-98)
[AF-98]: https://algorandfoundation.atlassian.net/browse/AF-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Error is displayed when accessing a closed voting session

---

src/xgov-dapp/package-lock.json
src/xgov-dapp/package.json
src/xgov-dapp/src/utils/useAlgoWalletProvider.ts

- Adds MyAlgo Wallet provider.
- Moves Exodus as last element
- https://algorandfoundation.atlassian.net/browse/AF-93

feat: add my algo wallet

---

src/xgov-dapp/src/features/vote/VoteResults.tsx
src/xgov-dapp/src/features/vote/index.tsx

- Display approved proposals according to a new formula (applies only for closed voting sessions)
- Jira: [AF-73](https://algorandfoundation.atlassian.net/browse/AF-73?atlOrigin=eyJpIjoiZGU2MGU2Y2Y4ZDVjNDRkM2IwODJiNWMxZDUyMzQ2YWIiLCJwIjoiaiJ9)
[AF-73]: https://algorandfoundation.atlassian.net/browse/AF-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Change the way we determine approved proposals

---

src/xgov-dapp/src/shared/ProposalCard.tsx

- Dangerously set HTML of the ProposalCard description Typography.
- Rely on parsing/importing of Proposal Description markdown for sanitation 
- https://algorandfoundation.atlassian.net/browse/AF-74

feat: render ProposalCard descriptions html

---

src/dapp/package.json
src/dapp/src/shared/IPFSGateway.ts

- adds semantic versioning to IPFS files
- uses `./src/dapp/package.json` as VERSION source
- uses `1.0.0` for undefined versions in IPFS
- https://algorandfoundation.atlassian.net/browse/AF-114

feat: add semantic versioning to ipfs assets

---

src/xgov-dapp/package-lock.json
src/xgov-dapp/package.json
src/xgov-dapp/src/features/vote-creation/RoundInfo.tsx

- Sanitize Proposal Descriptions
- https://algorandfoundation.atlassian.net/browse/AF-112

feat: sanitize vote description

---

src/dapp/package-lock.json
src/xgov-dapp/src/features/rounds/index.tsx
src/xgov-dapp/src/features/status/index.tsx

- Add xGov Guide link to the main page and status page
- Jira: [AF-105](https://algorandfoundation.atlassian.net/browse/AF-105)
[AF-105]: https://algorandfoundation.atlassian.net/browse/AF-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add xGov Guide link to the main page and status page

---

src/xgov-dapp/src/features/vote/VotingInstructions.tsx

- Add text to voting instructions card
- Jira: [ENG-56](https://algorandfoundation.atlassian.net/browse/ENG-56)
[ENG-56]: https://algorandfoundation.atlassian.net/browse/ENG-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Voting Instructions card on voting page - improve instructions text

---

src/xgov-dapp/src/features/status/EligibilityStatus.tsx
src/xgov-dapp/src/features/status/VotingSessionsTable.tsx
src/xgov-dapp/src/features/status/index.tsx

- Remove re-enroll button from xGov status page
- Show `Vote now` button in  xGov status page only if eligible
- Jira: [ENG-134](https://algorandfoundation.atlassian.net/browse/ENG-134)
[ENG-134]: https://algorandfoundation.atlassian.net/browse/ENG-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove re-enroll button and fix eligibility status

---

src/xgov-dapp/src/features/vote/index.tsx

- Adds filter to top of proposals list on smaller than large screens
- https://algorandfoundation.atlassian.net/browse/AF-120

fix: filter on smaller screens

---

src/build-a-bull/src/features/rounds/VotingRoundTile.tsx
src/build-a-bull/src/features/rounds/index.tsx
src/build-a-bull/src/features/vote-creation/RoundInfo.tsx
src/build-a-bull/src/features/vote-creation/review/index.tsx
src/build-a-bull/src/features/vote/VoteResults.tsx
src/build-a-bull/src/features/vote/VotingStats.tsx
src/build-a-bull/src/features/vote/index.tsx
src/build-a-bull/src/root.tsx
src/build-a-bull/src/shared/ProposalCard.tsx

- Refactors build-a-bull from `PARTITIONED_WEIGHTING` to `NO_SNAPSHOT`
- Tracking: https://algorandfoundation.atlassian.net/browse/ENG-67

refactor: build a bull set no snapshots

---

.github/workflows/release.yml
infrastructure/bin/infrastructure.ts

fix: update bab path for cloudfront

---

src/xgov-dapp/src/features/vote/VoteResults.tsx

- Add an option to download a CSV file with xgov results from the results page
- Jira: [ENG-16](https://algorandfoundation.atlassian.net/browse/ENG-16)
[ENG-16]: https://algorandfoundation.atlassian.net/browse/ENG-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Automated generation of the approved list for fund distribution

---

src/build-a-bull/src/components/siteHeader.tsx
src/build-a-bull/src/features/vote-creation/RoundInfo.tsx
src/build-a-bull/src/features/vote-creation/review/index.tsx
src/build-a-bull/src/features/vote/FilterMenu.tsx
src/build-a-bull/src/features/vote/VoteResults.tsx
src/build-a-bull/src/features/vote/VotingInstructions.tsx
src/build-a-bull/src/features/vote/VotingStats.tsx
src/build-a-bull/src/features/vote/index.tsx
src/build-a-bull/src/root.tsx
src/build-a-bull/src/shared/api.ts

- adds csv download for results
- cleans up UI elements and verbiage
- removes category from filter

refactor: bab UI elements

---

src/build-a-bull/src/components/siteHeader.tsx
src/build-a-bull/src/features/rounds/index.tsx
src/build-a-bull/src/features/vote/VoteResults.tsx
src/build-a-bull/src/features/vote/index.tsx
src/build-a-bull/src/shared/ProposalCard.tsx

- redirects to voting session
- removes back links and navigation
- fixes vote results display
- https://algorandfoundation.atlassian.net/browse/ENG-67

chore: redirect to active session

---

src/voting-metadata-api/package-lock.json
src/xgov-dapp/package-lock.json
src/xgov-dapp/package.json
src/xgov-dapp/src/utils/useAlgoWalletProvider.ts

- Remove MyAlgo wallet due to shutdown
- Jira: [ENG-180](https://algorandfoundation.atlassian.net/browse/ENG-180)
[ENG-180]: https://algorandfoundation.atlassian.net/browse/ENG-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove MyAlgo wallet

---

.github/workflows/release.yml

- pin release workflow due to breaking changes
- https://algorandfoundation.atlassian.net/browse/ENG-216

fix: pin release workflow

---

src/xgov-dapp/package.json
src/xgov-dapp/src/constants.ts
src/xgov-dapp/src/utils/common.ts

https://algorandfoundation.atlassian.net/browse/ENG-206
Changing the version to one that is beyond what the reserve list version will be supported for.

chore: ENG-206 turn off reserve lists

---

src/xgov-dapp/src/features/vote/VotingInstructions.tsx
src/xgov-dapp/src/features/vote/index.tsx

- disables input on passed questions
- checks latest state before submitting vote
- displays Dialog to reallocate votes
- https://algorandfoundation.atlassian.net/browse/ENG-211

feat: voter should not be able to vote on passed proposals (UI only)

---

src/build-a-bull/package-lock.json
src/build-a-bull/package.json
src/xgov-dapp/package-lock.json
src/xgov-dapp/package.json
src/xgov-dapp/src/shared/ProposalCard.tsx
src/xgov-dapp/src/shared/stats.ts

- Identify mock proposal by category ("Abstain" or "Mock")
- Distinguish mock from other proposals
- Ignore mock proposal in stats
- Jira: [ENG-222](https://algorandfoundation.atlassian.net/browse/ENG-222)
[ENG-222]: https://algorandfoundation.atlassian.net/browse/ENG-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: identify mock proposal by category ("Abstain" or "Mock")

---

src/xgov-dapp/src/features/status/InformationBox.tsx

- styles information panel in status page
- https://algorandfoundation.atlassian.net/browse/ENG-499

chore: format verbiage on status page

---

src/xgov-dapp/src/features/status/InformationBox.tsx

- Updates verbiage now that term pools have closed

release: production changes
